
INSERT INTO public.products (sku, model, slug, name, description, category, series, cpu, ram_gb, storage_gb, storage_type, os, form_factor, unit_price, has_wifi, has_4g, is_active, is_featured, warranty_months, warranty_type, stock_status, tags, image_url, thumbnail_url, gallery_urls)
VALUES
  ('gk1004', 'GK1004', 'gk1004', 'GK1004 — 10.4" Industrial Panel PC',
   'Panel PC อุตสาหกรรม 10.4" IP65 หน้าจอสัมผัส 10 จุด เลือกได้ทั้ง Intel/AMD/ARM รองรับ Windows/Linux/Android ไฟ 12-64V',
   'Industrial Panel PC', 'GK Series', 'Intel Core i3/i5/i7, AMD A6, ARM RK3288/RK3399', 8, 512, 'SSD', 'Windows/Linux/Android', 'Panel PC', 0,
   true, true, true, false, 12, 'carry_in', 'available',
   ARRAY['panel-pc','industrial','ip65','touch','10-inch'],
   'https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk1004-primary.png',
   'https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk1004-primary.png',
   NULL),

  ('gk1501', 'GK1501', 'gk1501', 'GK1501 — 15" Industrial Panel PC',
   'Panel PC อุตสาหกรรม 15" IP65 จอสัมผัส Capacitive 10 จุด รองรับ Core i5/i7 หลาย Gen เหมาะ HMI, SCADA, Factory Automation',
   'Industrial Panel PC', 'GK Series', 'Intel Core i5/i7 Gen3/Gen6', 8, 512, 'SSD', 'Windows/Linux', 'Panel PC', 0,
   true, true, true, false, 12, 'carry_in', 'available',
   ARRAY['panel-pc','industrial','ip65','touch','15-inch'],
   'https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk1501-primary.png',
   'https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk1501-primary.png',
   ARRAY['https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk1501-gallery-1.jpg','https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk1501-gallery-2.jpg','https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk1501-gallery-3.jpg']),

  ('gk1506', 'GK1506', 'gk1506', 'GK1506 (A15) — 15.6" Full HD Industrial Panel PC',
   'Panel PC อุตสาหกรรม 15.6" Full HD IP65 ทั้งตัว จอสัมผัส 10 จุด ความสว่างสูงสุด 1,000 nits ไฟ 9-36V Best Seller',
   'Industrial Panel PC', 'GK Series', 'Intel Pentium/Core i3/i5/i7 Gen5', 8, 512, 'SSD', 'Windows/Linux/IoT', 'Panel PC', 0,
   true, true, true, true, 12, 'carry_in', 'available',
   ARRAY['panel-pc','industrial','ip65','touch','15.6-inch','full-hd','best-seller'],
   'https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk1506-primary.jpg',
   'https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk1506-primary.jpg',
   ARRAY['https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk1506-gallery-1.jpg','https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk1506-gallery-2.jpg','https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk1506-gallery-3.jpg','https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk1506-gallery-4.jpg','https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk1506-gallery-5.jpg']),

  ('gk1901', 'GK1901', 'gk1901', 'GK1901 — 19" Industrial Panel PC',
   'Panel PC อุตสาหกรรม 19" IP65 จอสัมผัส 10 จุด รองรับ Core i5 Gen4/Gen8 และ Core i7 Gen3/Gen6 เหมาะ Control Room, SCADA',
   'Industrial Panel PC', 'GK Series', 'Intel Core i5 Gen4/Gen8, i7 Gen3/Gen6', 8, 512, 'SSD', 'Windows/Linux', 'Panel PC', 0,
   true, true, true, false, 12, 'carry_in', 'available',
   ARRAY['panel-pc','industrial','ip65','touch','19-inch'],
   'https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk1901-primary.jpg',
   'https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk1901-primary.jpg',
   NULL),

  ('gk2101', 'GK2101', 'gk2101', 'GK2101 — 21" Full HD Industrial Panel PC',
   'Panel PC อุตสาหกรรม 21" Full HD IP65 จอสัมผัส 10 จุด โครงอะลูมิเนียม+เหล็ก รองรับ 24/7 ไฟ 12-64V Flagship',
   'Industrial Panel PC', 'GK Series', 'Intel Core i5 Gen4-7, i7 Gen3/Gen6', 16, 512, 'SSD', 'Windows/Linux', 'Panel PC', 0,
   true, true, true, true, 12, 'carry_in', 'available',
   ARRAY['panel-pc','industrial','ip65','touch','21-inch','full-hd','flagship'],
   'https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk2101-primary.png',
   'https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk2101-primary.png',
   ARRAY['https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk2101-gallery-1.jpg','https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk2101-gallery-2.jpg','https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk2101-gallery-3.jpg'])

ON CONFLICT (sku) DO UPDATE SET
  model = EXCLUDED.model,
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  series = EXCLUDED.series,
  cpu = EXCLUDED.cpu,
  ram_gb = EXCLUDED.ram_gb,
  storage_gb = EXCLUDED.storage_gb,
  storage_type = EXCLUDED.storage_type,
  os = EXCLUDED.os,
  form_factor = EXCLUDED.form_factor,
  has_wifi = EXCLUDED.has_wifi,
  has_4g = EXCLUDED.has_4g,
  is_active = EXCLUDED.is_active,
  is_featured = EXCLUDED.is_featured,
  tags = EXCLUDED.tags,
  image_url = EXCLUDED.image_url,
  thumbnail_url = EXCLUDED.thumbnail_url,
  gallery_urls = EXCLUDED.gallery_urls,
  updated_at = now();
