-- Update GK variant products to inherit image_url from their parent models
UPDATE products SET image_url = 'https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk1004-primary.png', updated_at = now() WHERE sku = 'gk1004-v2' AND image_url IS NULL;

UPDATE products SET image_url = 'https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk1501-primary.png', gallery_urls = ARRAY['https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk1501-gallery-1.jpg','https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk1501-gallery-2.jpg','https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk1501-gallery-3.jpg'], updated_at = now() WHERE sku = 'gk1501-v2' AND image_url IS NULL;

UPDATE products SET image_url = 'https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk1506-primary.jpg', gallery_urls = ARRAY['https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk1506-gallery-1.jpg','https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk1506-gallery-2.jpg','https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk1506-gallery-3.jpg','https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk1506-gallery-4.jpg','https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk1506-gallery-5.jpg'], updated_at = now() WHERE sku = 'gk1506-v5' AND image_url IS NULL;

UPDATE products SET image_url = 'https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk1901-primary.jpg', updated_at = now() WHERE sku IN ('gk1901-i54200u-4gb-64gb-4g', 'gk1901corei-corei5-4gb-128gb-wifi') AND image_url IS NULL;

UPDATE products SET image_url = 'https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk2101-primary.png', gallery_urls = ARRAY['https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk2101-gallery-1.jpg','https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk2101-gallery-2.jpg','https://ugzdwmyylqmirrljtuej.supabase.co/storage/v1/object/public/product-images/gt-series/gk2101-gallery-3.jpg'], updated_at = now() WHERE sku = 'gk2101-v4' AND image_url IS NULL;