INSERT INTO public.suppliers (
  company_name,
  company_name_en,
  business_type,
  country,
  contact_name,
  contact_position,
  email,
  phone,
  website,
  skype,
  whatsapp,
  address,
  city,
  state_province,
  bank_name,
  bank_address,
  bank_account_number,
  bank_account_name,
  swift_code,
  bank_country,
  main_products,
  payment_terms,
  lead_time_days,
  currency,
  warranty_terms_free,
  warranty_terms_paid,
  default_price_terms,
  default_payment_terms,
  default_delivery_days,
  status,
  approved_at,
  is_preferred,
  quality_rating,
  notes
) VALUES (
  'Shenzhen Greenthinpc Technology Limited',
  'Shenzhen Greenthinpc Technology Limited',
  'manufacturer',
  'China',
  'Amy Zeng',
  'Sales Director',
  'amy@greenthinpc.com',
  '+8615989483512',
  'www.jieruicc.com',
  'amythinclient',
  '+8615989483512',
  'D1208, Moore City, Longgang Street Office, Longgang District',
  'Shenzhen',
  'Guangdong',
  'DBS Bank (Hong Kong) Limited',
  '11th Floor, The Center, 99 Queen''s Road Central, Central, Hong Kong',
  '7996 9056 658',
  'Shenzhen Greenthinpc Technology Limited',
  'DHBKHKHH',
  'Hong Kong',
  ARRAY['Mini PC', 'Industrial PC', 'Fanless PC', 'Panel PC', 'Box PC'],
  'TT 100% before shipping',
  7,
  'USD',
  '24 months warranty offered for free repair',
  '36 months warranty offered for pay-needed maintenance',
  'Ex-works',
  'TT 100% before shipping',
  '5-7 working days after confirmed payment',
  'approved',
  now(),
  true,
  4.5,
  'Imported from PI GTA20260409001 (09 Apr 2026). Bank Code: 016, Branch Code: 478. Remark: Price does not include tax/duty. Buyer handles custom clearance.'
)
ON CONFLICT DO NOTHING;