// Auto-generated by scripts/fetch_touchwork_galleries.py — DO NOT EDIT MANUALLY
// Maps (model, arch) → ordered list of gallery image URLs.
import.meta.glob; // marker

// Vite eager-import all gallery images as URLs
const modules = import.meta.glob('@/assets/touchwork/gallery/*/*.jpg', {
  eager: true,
  query: '?url',
  import: 'default',
}) as Record<string, string>;

type Arch = 'Monitor' | 'ARM' | 'X86';

// Manifest: model → arch → relative file names (in order)
const manifest: Record<string, Partial<Record<Arch, string[]>>> = {
  DM080NF: {
    Monitor: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "06.jpg", "07.jpg"],
    ARM: ["03.jpg", "06.jpg", "07.jpg"],
    X86: ["03.jpg", "04.jpg", "06.jpg", "07.jpg"],
  },
  DM080WG: {
    Monitor: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
    ARM: ["03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
  },
  DM101G: {
    Monitor: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
    ARM: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
    X86: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
  },
  DM104G: {
    Monitor: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
    ARM: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
    X86: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
  },
  DM121G: {
    Monitor: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
    ARM: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
    X86: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
  },
  DM15G: {
    Monitor: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
    ARM: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
    X86: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
  },
  DM156G: {
    Monitor: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
    ARM: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
    X86: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
  },
  DM17G: {
    Monitor: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
    ARM: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
    X86: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
  },
  DM19G: {
    Monitor: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
    ARM: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
    X86: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
  },
  DM215G: {
    Monitor: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
    ARM: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
    X86: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
  },
  GD101E: {
    Monitor: ["01.jpg", "02.jpg", "03.jpg", "04.jpg"],
    ARM: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
    X86: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg"],
  },
  GD133: {
    Monitor: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
    ARM: ["01.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
    X86: ["01.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
  },
  JD133: {
    Monitor: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg"],
    ARM: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
  },
  JD156B: {
    Monitor: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg"],
    ARM: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg"],
    X86: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
  },
  JD185B: {
    Monitor: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
    ARM: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg"],
    X86: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
  },
  JD215B: {
    Monitor: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
    ARM: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"],
    X86: ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg"],
  },
};

function resolve(model: string, arch: Arch, file: string): string | undefined {
  const key = Object.keys(modules).find((k) => k.endsWith(`/gallery/${model}-${arch}/${file}`));
  return key ? modules[key] : undefined;
}

// Files that are technical dimension drawings (front view + rear/mounting view)
// — sourced from touchwoipc and consistent across all 16 models.
const DIMENSION_FILES = new Set(["06.jpg", "07.jpg"]);

/** Get full gallery image URL list for a model + architecture (all images). */
export function getTouchWorkGallery(model: string, arch: Arch): string[] {
  const files = manifest[model]?.[arch] ?? [];
  return files.map((f) => resolve(model, arch, f)).filter((u): u is string => Boolean(u));
}

/** Product/lifestyle images only — dimension drawings excluded. */
export function getTouchWorkProductImages(model: string, arch: Arch): string[] {
  const files = manifest[model]?.[arch] ?? [];
  return files
    .filter((f) => !DIMENSION_FILES.has(f))
    .map((f) => resolve(model, arch, f))
    .filter((u): u is string => Boolean(u));
}

/** Dimension/mechanical drawings only (front + rear views). */
export function getTouchWorkDimensionImages(model: string, arch: Arch): string[] {
  const files = manifest[model]?.[arch] ?? [];
  return files
    .filter((f) => DIMENSION_FILES.has(f))
    .map((f) => resolve(model, arch, f))
    .filter((u): u is string => Boolean(u));
}

/** Interface I/O port diagram — image #04 in the touchwoipc gallery convention. */
export function getTouchWorkInterfaceImage(model: string, arch: Arch): string | undefined {
  const files = manifest[model]?.[arch] ?? [];
  if (!files.includes("04.jpg")) return undefined;
  return resolve(model, arch, "04.jpg");
}

export const touchworkGalleryManifest = manifest;
